### ISSUE TITLE
 Could not find marketplace-zip-signer-cli-0.1.19.jar 

### ISSUE THREAD

**Issue by maiqingqiang** [JetBrains/marketplace-zip-signer#197]
<img width="1865" alt="image" src="https://github.com/JetBrains/marketplace-zip-signer/assets/1825679/7dfa983c-b9d1-4805-a8ab-fb4454643239">

404:  https://repo.maven.apache.org/maven2/org/jetbrains/marketplace-zip-signer-cli/0.1.19/marketplace-zip-signer-cli-0.1.19.jar

<img width="1140" alt="image" src="https://github.com/JetBrains/marketplace-zip-signer/assets/1825679/da3b3f79-23b6-4613-be9c-28a54721ee45">

@kesarevs @hsz

**Comment by jansorg** [comment]
https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/tasks/DownloadZipSignerTask.kt#L76 is referencing the `.jar` file, which was previously published instead of the `-all.jar` file. Would it be possible to restore the `.jar` file because every Gradle-based JetBrains plugin project which is using signing is now unable to publish new releases, I think.

**Comment by hsz** [comment]
Can you please verify if the issue is gone now on your end?

**Comment by maiqingqiang** [comment]
> Can you please verify if the issue is gone now on your end?

 Returned to normal.
